# Generated by Django 3.2.18 on 2023-03-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleBook', models.CharField(max_length=255)),
                ('time_minutesBook', models.IntegerField()),
                ('ingredientsBook', models.CharField(max_length=255)),
            ],
        ),
    ]
