# Generated by Django 3.2.18 on 2023-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='id',
            new_name='recipe_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
